Added Authentication & Authorization using Spring Security and enhanced the endpoints to use new exceptions.
Daniel-W-Innes/SYSC4806-Project-Backend pull request #54
Opened 2022-03-23 19:47 UTC by aelsammak

Added Authentication & Authorization using Spring Security. JWT is used for authentication. Roles needed to be added to the model so that Spring Security can allow only specific users to access certain endpoints. The two roles added so far are ROLE_SURVEYOR and ROLE_ADMIN. ROLE_SURVEYOR is added by default when a new Surveyor is created.

2022-03-23 20:17 UTC, aelsammak commented
Builds are failing due to tests. Tests need to be updated to include authentication. For instance, a surveyor needs to first be created and then sign in. Once successfully signed in, the request response will give you the access_token in which you will pass as a header to make requests that require authorization such as creating a survey. The header will look like this:
Authorization: "Bearer {access_token}"
For people writing tests, we can have a chat in discord for further clarification on this.

2022-03-24 14:20 UTC, Daniel-W-Innes requested changes

2022-03-24 21:04 UTC, aelsammak commented
**NOTE**: Before merging this PR, I need to specify all the new endpoints we add to the SecurityConfig so that we can authorize who is making the request.

2022-03-25 03:17 UTC, Daniel-W-Innes approved these changes

2022-03-25 03:17 UTC, merged